### ISSUE TITLE
Access to the whole Drive not allowed

### ISSUE THREAD

**Issue by mvysny** [googlearchive/drive-android-quickstart#18]
I'm trying to use this API to access all files on user's Drive, but it is not possible:
1. Using `Drive.SCOPE_FILE` only lists `New Folder` as a child of the root folder (`client.rootFolder`)
2. Using just `Scope("https://www.googleapis.com/auth/drive.readonly")` fails with:
```
java.lang.IllegalArgumentException: You must request a Drive scope in order to interact with the Drive API.
       at com.google.android.gms.common.internal.zzbq.checkArgument(Unknown Source)
       at com.google.android.gms.drive.Drive.zza(Unknown Source)
       at com.google.android.gms.drive.Drive.getDriveResourceClient(Unknown Source)
```
3. Using both scopes: `requestScopes(Drive.SCOPE_FILE, Scope("https://www.googleapis.com/auth/drive.readonly"))` seems to ignore the latter one and still only lists the `New Folder`

**Comment by mvysny** [comment]
4. Passing the scope of fails with an exception:
```
E/ClientConnectOperation: Handling authorization failure
                                                          nzh: Authorization failed: Unsupported scope: https://www.googleapis.com/auth/drive
                                                              at nzl.a(:com.google.android.gms@11951448:25)
                                                              at nvy.<init>(:com.google.android.gms@11951448:26)
                                                              at nxh.a(:com.google.android.gms@11951448:72)
                                                              at swi.run(:com.google.android.gms@11951448:11)
                                                              at mvc.run(:com.google.android.gms@11951448:26)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                              at nak.run(:com.google.android.gms@11951448)
                                                              at java.lang.Thread.run(Thread.java:761)
```
In its current state the API doesn't allow to iterate over the whole Drive, and thus it is useless to me.
